// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DomclusterService_Publish_FullMethodName = "/domcluster.DomclusterService/Publish"
)

// DomclusterServiceClient is the client API for DomclusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomclusterServiceClient interface {
	// 通用发布-订阅接口
	Publish(ctx context.Context, opts ...grpc.CallOption) (DomclusterService_PublishClient, error)
}

type domclusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomclusterServiceClient(cc grpc.ClientConnInterface) DomclusterServiceClient {
	return &domclusterServiceClient{cc}
}

func (c *domclusterServiceClient) Publish(ctx context.Context, opts ...grpc.CallOption) (DomclusterService_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &DomclusterService_ServiceDesc.Streams[0], DomclusterService_Publish_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &domclusterServicePublishClient{stream}
	return x, nil
}

type DomclusterService_PublishClient interface {
	Send(*PublishRequest) error
	Recv() (*PublishResponse, error)
	grpc.ClientStream
}

type domclusterServicePublishClient struct {
	grpc.ClientStream
}

func (x *domclusterServicePublishClient) Send(m *PublishRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *domclusterServicePublishClient) Recv() (*PublishResponse, error) {
	m := new(PublishResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DomclusterServiceServer is the server API for DomclusterService service.
// All implementations must embed UnimplementedDomclusterServiceServer
// for forward compatibility
type DomclusterServiceServer interface {
	// 通用发布-订阅接口
	Publish(DomclusterService_PublishServer) error
	mustEmbedUnimplementedDomclusterServiceServer()
}

// UnimplementedDomclusterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDomclusterServiceServer struct {
}

func (UnimplementedDomclusterServiceServer) Publish(DomclusterService_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedDomclusterServiceServer) mustEmbedUnimplementedDomclusterServiceServer() {}

// UnsafeDomclusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomclusterServiceServer will
// result in compilation errors.
type UnsafeDomclusterServiceServer interface {
	mustEmbedUnimplementedDomclusterServiceServer()
}

func RegisterDomclusterServiceServer(s grpc.ServiceRegistrar, srv DomclusterServiceServer) {
	s.RegisterService(&DomclusterService_ServiceDesc, srv)
}

func _DomclusterService_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DomclusterServiceServer).Publish(&domclusterServicePublishServer{stream})
}

type DomclusterService_PublishServer interface {
	Send(*PublishResponse) error
	Recv() (*PublishRequest, error)
	grpc.ServerStream
}

type domclusterServicePublishServer struct {
	grpc.ServerStream
}

func (x *domclusterServicePublishServer) Send(m *PublishResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *domclusterServicePublishServer) Recv() (*PublishRequest, error) {
	m := new(PublishRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DomclusterService_ServiceDesc is the grpc.ServiceDesc for DomclusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomclusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domcluster.DomclusterService",
	HandlerType: (*DomclusterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _DomclusterService_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
